const main = () => document.getElementById("main")
const nameInput = () => document.getElementById("name")
const cityInput = () => document.getElementById("city")
const styleInput = () => document.getElementById("style")
const form = () => document.getElementById("form")
const formLink = () => document.getElementById("form-link")
const restaurantsLink = () => document.getElementById("restaurants-link")